---
ansible_version_tested:
  major: 2
  minor: 13

# ! Debugging Enabled
playbook_debugging_enabled: false

# SNMP OIDs per device type mapping
device_type_oid_mapping:
  common_oids:
    - '"1.3.6.1.2.1.1.1.0"' # sysDescr
    - '"1.3.6.1.2.1.1.3.0"' # sysUpTime
    - '"1.3.6.1.2.1.1.5.0"' # sysName

  # TODO Example to add vendor-specific OIDs
  # cisco:
  #   ws-c2960tt-l:
  #     - 0.1.2.3.4.5

vault_elastic_secret_path: secret/data/logstash
vault_snmp_secret_path: secret/data/snmp

# Values from Vault
logstash_secret: "{{ lookup('hashi_vault',
  'secret={{ vault_elastic_secret_path }} token={{ VAULT_TOKEN }} validate_certs=false url={{ VAULT_URL }}') }}"
snmp_secret: "{{ lookup('hashi_vault',
  'secret={{ vault_snmp_secret_path }} token={{ VAULT_TOKEN }} validate_certs=false url={{ VAULT_URL }}') }}"
