---
ansible_version_tested:
  major: 2
  minor: 13

# SNMP OIDs per device type mapping
device_type_oid_mapping:
  common_oids:
    - '"1.3.6.1.2.1.1.1.0"' # sysDescr
    - '"1.3.6.1.2.1.1.3.0"' # sysUpTime
    - '"1.3.6.1.2.1.1.5.0"' # sysName

  # TODO Example to add vendor-specific OIDs
  # cisco:
  #   ws-c2960tt-l:
  #     - 0.1.2.3.4.5

vault_elastic_secret_path: secret/data/logstash
vault_snmp_secret_path: secret/data/snmp

snmp_username: '<username from Vault>'
snmp_auth_protocol: 'auth_proto'
snmp_auth_pass: 'auth_pass'
snmp_priv_protocol: 'priv_proto'
snmp_priv_pass: 'priv_pass'
snmp_security_level: 'sec_level'
