- name: Logstash dynamic pipeline updater
  hosts: localhost
  # ! Grouping is performed by inventory plugin
  # hosts: tags_snmp-enabled
  gather_facts: false
  become: false

  vars_files:
    - vars/common.yaml

  tasks:
    - name: MAIN | Input validation
      include_tasks: "input_validation.yaml"

    # ! Plugin netbox.netbox.nb_lookup requires following environment variables:
    # query a list of devices in a playbook
    # https://docs.ansible.com/ansible/latest/collections/netbox/netbox/nb_lookup_lookup.html
    # - NETBOX_API
    # - NETBOX_TOKEN
    - name: MAIN | Query list of devices from NetBox
      include_tasks: "add_hosts.yaml"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
          api_filter='has_primary_ip=true tags=snmp-enabled' ) }}"
      loop_control:
        label: "{{ netbox_device.value.name }}"
        loop_var: netbox_device

    # ! DEBUG
    - name: DEBUG
      debug:
        var: snmp_hosts_list
      when:
        - playbook_debugging_enabled | bool

    # ! DEBUG
    - name: DEBUG
      debug:
        var: logstash_secret
      when:
        - playbook_debugging_enabled | bool

    # ! DEBUG
    - name: DEBUG
      debug:
        var: snmp_secret
      when:
        - playbook_debugging_enabled | bool

    # For the details see Elastic API Documentation
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/logstash-api-put-pipeline.html
    - name: MAIN | Populate values for SNMP configuration
      set_fact:
        logstash_snmp_config: >
          input {
            snmp {
              hosts => [{{ snmp_hosts_list | join(',') }}]
              get => [{{ device_type_oid_mapping.common_oids | join(',') }}]
              security_name => "{{ snmp_secret['username'] }}"
              auth_protocol => "{{ snmp_secret['auth_protocol'] }}"
              auth_pass => "{{ snmp_secret['auth_pass'] }}"
              priv_protocol => "{{ snmp_secret['priv_protocol'] }}"
              priv_pass => "{{ snmp_secret['priv_pass'] }}"
              security_level => "{{ snmp_secret['security_level'] }}"
            }
          }

    - name: MAIN | Prepare body for API call
      set_fact:
        logstash_api_call_body:
          description: "Network SNMP"
          last_modified: "{{ lookup('pipe', 'date --utc +%FT%T.%3NZ') }}"
          pipeline_metadata:
            type: "logstash_pipeline"
          username: "elastic"
          pipeline: "{{ logstash_snmp_config }}"
          pipeline_settings:
            pipeline.workers: 1
            pipeline.batch.size: 125
            pipeline.batch.delay: 50
            queue.type: "memory"
            queue.max_bytes: "1gb"
            queue.checkpoint.writes: 1024

    # ! DEBUG
    - name: DEBUG
      debug:
        var: logstash_api_call_body
      when:
        - playbook_debugging_enabled | bool

    # ! DEBUG
    - name: DEBUG
      debug:
        var: ELASTIC_URL
      when:
        - playbook_debugging_enabled | bool

    - name: MAIN | Update Logstash SNMP Pipeline configuration
      uri:
        body_format: json
        method: PUT
        url: "{{ ELASTIC_URL }}/_logstash/pipeline/{{ PIPELINE_ID }}"
        url_username: "{{ logstash_secret['username'] }}"
        url_password: "{{ logstash_secret['password'] }}"
        timeout: 30
        body: "{{ logstash_api_call_body }}"
        status_code:
          - 200
          - 201
      delegate_to: localhost
      vars:
        ansible_connection: local
